# Generated by Django 5.1.5 on 2025-03-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('caketype', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('flavor', models.CharField(max_length=100)),
                ('availability', models.CharField(choices=[('birthday', 'Birthday'), ('wedding', 'Wedding'), ('anniversary', 'Anniversary'), ('monthsary', 'Monthsary'), ('christening', 'Christening'), ('debut', 'Debut'), ('gender_reveal', 'Gender Reveal'), ('christmas', 'Christmas'), ('new_year', 'New Year')], max_length=20)),
                ('group_by', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cake_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('cake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cake')),
            ],
        ),
    ]
