# Generated by Django 5.1.5 on 2025-03-03 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_alter_cake_availability_alter_cake_group_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('add_price', models.IntegerField()),
                ('cake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cake')),
            ],
        ),
    ]
