# Generated by Django 5.1.5 on 2025-03-03 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_layer', models.IntegerField()),
                ('add_price', models.IntegerField()),
                ('cake_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cake.cake')),
            ],
        ),
    ]
