# Generated by Django 5.1.5 on 2025-03-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0005_filling'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filling',
            name='image',
            field=models.ImageField(upload_to='Cakes/Filling'),
        ),
    ]
