# Generated by Django 5.1.5 on 2025-03-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0006_alter_filling_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='main_pic',
            field=models.ImageField(null=True, upload_to='cake/main/'),
        ),
    ]
