# Generated by Django 5.1.5 on 2025-03-06 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0007_cake_main_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='rating',
            field=models.IntegerField(default=5),
        ),
    ]
