# Generated by Django 5.1.5 on 2025-03-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0008_cake_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='rating',
            field=models.CharField(default='xxxxx', max_length=5),
        ),
    ]
