# Generated by Django 5.1.5 on 2025-05-19 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_cake_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='caketype',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='flavor',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='rating',
        ),
    ]
