# Generated by Django 5.1.5 on 2025-01-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('initname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('phonenum', models.IntegerField()),
                ('emailadd', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=50)),
            ],
        ),
    ]
