# Generated by Django 5.1.5 on 2025-01-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phonenum',
            field=models.CharField(max_length=11),
        ),
    ]
