# Generated by Django 5.1.5 on 2025-03-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_phonenum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='emailadd',
            new_name='email_add',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='init_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='initname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phonenum',
            new_name='phone_num',
        ),
        migrations.AddField(
            model_name='customer',
            name='contact_num',
            field=models.IntegerField(default='09123456789'),
        ),
        migrations.AddField(
            model_name='customer',
            name='home_address',
            field=models.CharField(default='Daraga', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='Customer/Profile Picture'),
        ),
    ]
