# Generated by Django 5.1.5 on 2025-03-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_cart_is_ordered_order_cart_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not paid', 'not paid'), ('paid', 'paid'), ('in progress', 'in progress'), ('delivered', 'delivered')], default='not paid', max_length=15),
            preserve_default=False,
        ),
    ]
