# Generated by Django 5.1.5 on 2025-03-17 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cart_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='order.order'),
        ),
    ]
