# Generated by Django 5.1.5 on 2025-04-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cart_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not paid', 'not paid'), ('paid', 'paid'), ('in progress', 'in progress'), ('halfway', 'halfway'), ('almost finished', 'almost finished'), ('delivered', 'delivered'), ('fully paid', 'fully paid')], default='not paid', max_length=15),
        ),
    ]
