# Generated by Django 5.1.5 on 2025-05-11 03:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0009_alter_cake_rating'),
        ('order', '0010_alter_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cake',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cake.cake'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date(2025, 5, 18)),
        ),
    ]
