# Generated by Django 5.1.5 on 2025-02-27 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_receiver_remove_message_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_sender',
            new_name='is_channel_sender',
        ),
    ]
