# Generated by Django 5.1.5 on 2025-04-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0006_alter_cart_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_prof', models.ImageField(upload_to='Transactions/images/')),
                ('reference_number', models.CharField(max_length=15)),
                ('amount', models.IntegerField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='order.order')),
            ],
        ),
    ]
