# Generated by Django 5.1.5 on 2025-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('not_accepted', 0), ('accepted', 1)], default=0, max_length=20),
        ),
    ]
