# Generated by Django 5.1.5 on 2025-04-22 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.IntegerField(choices=[(0, 'not_accepted'), (1, 'accepted')], default=0),
        ),
    ]
