# Generated by Django 5.1.5 on 2025-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'not_accepted'), (1, 'accepted')], default=0),
        ),
    ]
