# Generated by Django 5.1.5 on 2025-05-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_type',
            field=models.IntegerField(choices=[(0, 'partial payment'), (1, 'completion payment')], default=0),
        ),
    ]
