# Generated by Django 5.1.5 on 2025-05-06 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cake', '0009_alter_cake_rating'),
        ('customer', '0010_alter_customer_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(1, 'Very Dissatisfied'), (2, 'Dissatisfied'), (3, 'Neutral or Average'), (4, 'Satisfied'), (5, 'Very Satisfied')], default=1)),
                ('comment', models.TextField()),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='cake.cake')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='customer.customer')),
            ],
        ),
    ]
