# Generated by Django 5.1.5 on 2025-05-13 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
